/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

// Clean up old caches and take control immediately
cleanupOutdatedCaches();
self.skipWaiting();
clientsClaim();

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Strip token query param from URL for cache key (tokens refresh frequently)
const stripTokenFromCacheKey = {
  cacheKeyWillBeUsed: async ({ request }: { request: Request }) => {
    const url = new URL(request.url);
    url.searchParams.delete('token');
    return url.toString();
  },
};

// Cache naming convention:
// - photodrop:group:* = group-scoped (cleared on group switch)
// - photodrop:user:* = user-scoped (cleared on logout along with group caches)

// Cache thumbnails with cache-first strategy (no expiry, small files ~200KB)
registerRoute(
  ({ url }) => url.pathname.match(/\/photos\/[^/]+\/thumbnail$/),
  new CacheFirst({
    cacheName: 'photodrop:group:thumbnails',
    plugins: [
      stripTokenFromCacheKey,
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache full-size photos with cache-first strategy (max 20 entries, purge on quota error)
registerRoute(
  ({ url }) => url.pathname.match(/\/photos\/[^/]+\/download$/),
  new CacheFirst({
    cacheName: 'photodrop:group:fullsize',
    plugins: [
      stripTokenFromCacheKey,
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Cache photo list API responses with network-first (prefer fresh data, cache fallback when offline)
registerRoute(
  ({ url }) => url.pathname === '/photos',
  new NetworkFirst({
    cacheName: 'photodrop:group:photo-list',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// Cache user/group info API responses with network-first (prefer fresh data)
registerRoute(
  ({ url }) =>
    url.pathname === '/users/me' ||
    url.pathname === '/groups' ||
    url.pathname.match(/\/groups\/[^/]+\/members$/),
  new NetworkFirst({
    cacheName: 'photodrop:user:api',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// Handle push notifications
self.addEventListener('push', (event) => {
  if (!event.data) {
    return;
  }

  try {
    const payload = event.data.json();

    const options: NotificationOptions = {
      body: payload.body,
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      data: payload.data,
      tag: payload.data?.photoId || 'photodrop-notification',
    };

    event.waitUntil(self.registration.showNotification(payload.title, options));
  } catch (error) {
    console.error('Error showing notification:', error);
  }
});

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const url = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If app is already open, focus it and navigate
      for (const client of clientList) {
        if ('focus' in client && 'navigate' in client) {
          return client.focus().then(() => (client as WindowClient).navigate(url));
        }
      }
      // Otherwise open a new window
      return self.clients.openWindow(url);
    })
  );
});
