/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

// Clean up old caches
cleanupOutdatedCaches();

// A new worker waits until the user accepts the update (SwUpdatePrompt posts
// SKIP_WAITING), so we never reload mid-session unexpectedly. The activate
// handler below still purges auth-scoped caches when the new worker takes over.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

clientsClaim();

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Strip token query param from URL for cache key (tokens refresh frequently)
const stripTokenFromCacheKey = {
  cacheKeyWillBeUsed: async ({ request }: { request: Request }) => {
    const url = new URL(request.url);
    url.searchParams.delete('token');
    return url.toString();
  },
};

// Cache naming convention:
// - photodrop:group:* = group-scoped (cleared on group switch)
// - photodrop:user:* = user-scoped (cleared on logout along with group caches)
const authScopedRuntimeCaches = [
  'photodrop:group:thumbnails',
  'photodrop:group:fullsize',
  'photodrop:group:photo-list',
  'photodrop:user:api',
];

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all(authScopedRuntimeCaches.map((cacheName) => caches.delete(cacheName)))
  );
});

// Match only same-origin requests so we don't intercept cross-origin API/images (e.g. dev API on another port).
// The SW controls the page and sees all fetches; without this guard, CacheFirst can capture those requests.
//
// Consequence: the runtime caches below only engage when the API is same-origin
// with the page — local dev (Vite proxies /api/* to the backend) or a deploy
// that fronts the API on the page's own origin. The default production build
// (scripts/deploy.sh sets VITE_API_URL=https://$API_DOMAIN) talks to a separate
// API subdomain, so image/API requests are cross-origin and intentionally
// bypass these caches; combined with the backend's `no-store`, default
// production has no persistent image cache and refetches on cold loads. In-app
// images are still deduped/cached in memory for the session by
// useAuthenticatedImage's blob-URL LRU. Persistent cross-origin caching would
// require a same-origin /api proxy (or allowlisting the API origin here plus
// the matching CORS work) and is deliberately left out for now.
const isSameOrigin = (url: URL) => url.origin === self.location.origin;

// These runtime caches hold authenticated, user-private content. That is safe
// because each cache is scoped to this browser and is purged on logout and
// group switch (clearAllUserCaches / clearGroupCaches) and on SW activation
// (above). Photo URLs are immutable and group-scoped, so a cached entry is only
// ever valid for the same user's own content.

// Cache thumbnails with cache-first strategy (no expiry, small files ~200KB)
// (?:api\/)? prefix handles local dev where vite proxies /api/* to backend
registerRoute(
  ({ url }) => isSameOrigin(url) && url.pathname.match(/^\/(?:api\/)?photos\/[^/]+\/thumbnail$/),
  new CacheFirst({
    cacheName: 'photodrop:group:thumbnails',
    // Image responses set `Vary: Authorization`; ignore it so a refreshed
    // access token doesn't invalidate every cached image.
    matchOptions: { ignoreVary: true },
    plugins: [
      stripTokenFromCacheKey,
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache full-size photos with cache-first strategy (max 20 entries, purge on quota error)
registerRoute(
  ({ url }) => isSameOrigin(url) && url.pathname.match(/^\/(?:api\/)?photos\/[^/]+\/download$/),
  new CacheFirst({
    cacheName: 'photodrop:group:fullsize',
    matchOptions: { ignoreVary: true },
    plugins: [
      stripTokenFromCacheKey,
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Cache photo list API responses with network-first (prefer fresh data, cache fallback when offline)
registerRoute(
  ({ url }) => isSameOrigin(url) && url.pathname.match(/^\/(?:api\/)?photos$/),
  new NetworkFirst({
    cacheName: 'photodrop:group:photo-list',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 10,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// Cache user/group info API responses with network-first (prefer fresh data)
registerRoute(
  ({ url }) =>
    isSameOrigin(url) &&
    (url.pathname.match(/^\/(?:api\/)?users\/me$/) ||
      url.pathname.match(/^\/(?:api\/)?groups$/) ||
      url.pathname.match(/^\/(?:api\/)?groups\/[^/]+\/members$/)),
  new NetworkFirst({
    cacheName: 'photodrop:user:api',
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// Handle push notifications
self.addEventListener('push', (event) => {
  if (!event.data) {
    return;
  }

  try {
    const payload = event.data.json();

    const options: NotificationOptions = {
      body: payload.body,
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      data: payload.data,
      tag: payload.data?.photoId || 'photodrop-notification',
    };

    event.waitUntil(self.registration.showNotification(payload.title, options));
  } catch (error) {
    console.error('Error showing notification:', error);
  }
});

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const url = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If app is already open, focus it and navigate
      for (const client of clientList) {
        if ('focus' in client && 'navigate' in client) {
          return client.focus().then(() => (client as WindowClient).navigate(url));
        }
      }
      // Otherwise open a new window
      return self.clients.openWindow(url);
    })
  );
});
